files:
  - source: /localization/en/*.json
    translation: /localization/%two_letters_code%/%original_file_name%
  - source: /assets/images/previews/en/*.png
    translation: /assets/images/previews/%two_letters_code%/%original_file_name%
